stages:
 - build
 - test
 - upload
 - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/socks-router-linux-amd64/${CI_COMMIT_TAG}"
  # Not `.cargo` because it can be used for crate-specific config
  # This override is necessary for caching to work
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo-home"

image: "rust:1-bullseye"

cache: &global_cache
  paths:
    - target
    - "${CARGO_HOME}/bin"
    - "${CARGO_HOME}/registry/index"
    - "${CARGO_HOME}/registry/cache"
    - "${CARGO_HOME}/git/db"
  unprotect: true

build:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build --release --verbose
  artifacts:
    paths:
      - target/release/socks-router

test:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  script:
    - rustc --version && cargo --version
    - cargo test --release --verbose

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  # Only needs the binary (artifact)
  cache: []
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file target/release/socks-router "${PACKAGE_REGISTRY_URL}/socks-router"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  cache: []
  script:
    - echo "release job"
  release:
    tag_name: $CI_COMMIT_TAG
    description: 'Automated release'
    assets:
      links:
        - name: 'socks-router'
          url: "${PACKAGE_REGISTRY_URL}/socks-router"

publish:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  cache: []
  script:
    - rustc --version && cargo --version
    # Ensure same version as the tag
    - |
      grep -qE '^\s*version\s*=\s*"'"${CI_COMMIT_TAG}"'"' Cargo.toml
    - cargo publish
